global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "ingestor"
    static_configs:
      - targets: ["ingestor:9100"]
  - job_name: "ai-worker"
    static_configs:
      - targets: ["ai-worker:9101"]
